# Generated by Django 4.0.1 on 2022-01-31 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choises',
            new_name='Choise',
        ),
    ]
